---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capmet-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capmet-app
  template:
    metadata:
      labels:  
        app: capmet-app
    spec:
      containers:
        - name: capmet
          image: wsrfreitas/capmet:latest
---
apiVersion: v1
kind: Service
metadata:
  name: capmet-service
spec:
  selector:
    app: capmet-app
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer

